python rename_procs.py --inputPath rawRootFiles/0l4tau/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/0l4tau/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/0l4tau/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/1l3tau/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/1l3tau/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/1l3tau/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/2l2tau/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/2l2tau/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/2l2tau/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/3l1tau/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/3l1tau/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/3l1tau/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/3l/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/3l/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/3l/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/4l/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/4l/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/4l/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/2lss/2016/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/2lss/2017/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/2lss/2018/rebinned_quantile/
python rename_procs.py --inputPath rawRootFiles/ZZCR/2016/rebinned/
python rename_procs.py --inputPath rawRootFiles/ZZCR/2017/rebinned/
python rename_procs.py --inputPath rawRootFiles/ZZCR/2018/rebinned/
python rename_procs.py --inputPath rawRootFiles/WZCR/2016/rebinned/
python rename_procs.py --inputPath rawRootFiles/WZCR/2017/rebinned/
python rename_procs.py --inputPath rawRootFiles/WZCR/2018/rebinned/
